apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: update-test-policy-namespace
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-5 Access Restrictions for Change
    integrityshield.io/message: YXBpVmVyc2lvbjogcG9saWN5Lm9wZW4tY2x1c3Rlci1tYW5hZ2VtZW50LmlvL3YxCmtpbmQ6IFBvbGljeQptZXRhZGF0YToKICBuYW1lOiB1cGRhdGUtdGVzdC1wb2xpY3ktbmFtZXNwYWNlCiAgYW5ub3RhdGlvbnM6CiAgICBwb2xpY3kub3Blbi1jbHVzdGVyLW1hbmFnZW1lbnQuaW8vc3RhbmRhcmRzOiBOSVNUIFNQIDgwMC01MwogICAgcG9saWN5Lm9wZW4tY2x1c3Rlci1tYW5hZ2VtZW50LmlvL2NhdGVnb3JpZXM6IENNIENvbmZpZ3VyYXRpb24gTWFuYWdlbWVudAogICAgcG9saWN5Lm9wZW4tY2x1c3Rlci1tYW5hZ2VtZW50LmlvL2NvbnRyb2xzOiBDTS01IEFjY2VzcyBSZXN0cmljdGlvbnMgZm9yIENoYW5nZQpzcGVjOgogIHJlbWVkaWF0aW9uQWN0aW9uOiBlbmZvcmNlCiAgZGlzYWJsZWQ6IGZhbHNlCiAgcG9saWN5LXRlbXBsYXRlczoKICAtIG9iamVjdERlZmluaXRpb246CiAgICAgIGFwaVZlcnNpb246IHBvbGljeS5vcGVuLWNsdXN0ZXItbWFuYWdlbWVudC5pby92MQogICAgICBraW5kOiBDb25maWd1cmF0aW9uUG9saWN5CiAgICAgIG1ldGFkYXRhOgogICAgICAgIG5hbWU6IHVwZGF0ZS10ZXN0LXBvbGljeS10ZXN0LW5hbWVzcGFjZQogICAgICBzcGVjOgogICAgICAgIHJlbWVkaWF0aW9uQWN0aW9uOiBlbmZvcmNlCiAgICAgICAgc2V2ZXJpdHk6IEhpZ2gKICAgICAgICBvYmplY3QtdGVtcGxhdGVzOgogICAgICAgIC0gY29tcGxpYW5jZVR5cGU6IG11c3RoYXZlCiAgICAgICAgICBvYmplY3REZWZpbml0aW9uOgogICAgICAgICAgICBraW5kOiBOYW1lc3BhY2UKICAgICAgICAgICAgYXBpVmVyc2lvbjogdjEKICAgICAgICAgICAgbWV0YWRhdGE6CiAgICAgICAgICAgICAgbmFtZTogdXBkYXRlLXRlc3QtcG9saWN5LXRlc3QtbnMKLS0tCmFwaVZlcnNpb246IHBvbGljeS5vcGVuLWNsdXN0ZXItbWFuYWdlbWVudC5pby92MQpraW5kOiBQbGFjZW1lbnRCaW5kaW5nCm1ldGFkYXRhOgogIG5hbWU6IHVwZGF0ZS10ZXN0LWJpbmRpbmctcG9saWN5LW5hbWVzcGFjZQpwbGFjZW1lbnRSZWY6CiAgbmFtZTogdXBkYXRlLXRlc3QtcGxhY2VtZW50LXBvbGljeS1uYW1lc3BhY2UKICBraW5kOiBQbGFjZW1lbnRSdWxlCiAgYXBpR3JvdXA6IGFwcHMub3Blbi1jbHVzdGVyLW1hbmFnZW1lbnQuaW8Kc3ViamVjdHM6Ci0gbmFtZTogdXBkYXRlLXRlc3QtcG9saWN5LW5hbWVzcGFjZQogIGtpbmQ6IFBvbGljeQogIGFwaUdyb3VwOiBwb2xpY3kub3Blbi1jbHVzdGVyLW1hbmFnZW1lbnQuaW8KLS0tCmFwaVZlcnNpb246IGFwcHMub3Blbi1jbHVzdGVyLW1hbmFnZW1lbnQuaW8vdjEKa2luZDogUGxhY2VtZW50UnVsZQptZXRhZGF0YToKICBuYW1lOiB1cGRhdGUtdGVzdC1wbGFjZW1lbnQtcG9saWN5LW5hbWVzcGFjZQpzcGVjOgogIGNsdXN0ZXJDb25kaXRpb25zOgogIC0gc3RhdHVzOiAiVHJ1ZSIKICAgIHR5cGU6IE1hbmFnZWRDbHVzdGVyQ29uZGl0aW9uQXZhaWxhYmxlCiAgY2x1c3RlclNlbGVjdG9yOgogICAgbWF0Y2hFeHByZXNzaW9uczoKICAgIC0ge2tleTogZW52aXJvbm1lbnQsIG9wZXJhdG9yOiBJbiwgdmFsdWVzOiBbImRldiJdfQo=
    integrityshield.io/signature: LS0tLS1CRUdJTiBQR1AgU0lHTkFUVVJFLS0tLS0KCmlRRlBCQUFCQ0FBNUZpRUUrU2psQVN5SlZoa3FGVDNLT1Q2Y3pnLzRpcmtGQW1BWkRaWWJIR2hwY205cmRXNXAKTG10cGRHRm9ZWEpoTVVCcFltMHVZMjl0QUFvSkVEaytuTTRQK0lxNWpqZ0grd1loUWhIWExUUEx2WDBtZDdxMgpyVnBwTnZuWW1ybHNLUDJYM0NwTFI1cWEvcElOQmJVZy9PM01zam5MYS9KdmYxQy91WXRFYjVaMFVjWi94YUwvCjExQ2ladHRJaUdlZzZwOUE0cXFmQml1ekhGaHZtUHFQTEtFa2ZJcmw4V1Juc2VoT21TLzlBUDJNclo3V0JnWk8KMm8wak9MZUo4Um0wYzRFOHljUFBvTWlWeENlUUt3WktTVC9IckZDckhEVjZnM3ZNcUVFNVVBNnBNU2hCeFduNgpOY2tKUkkxMUFISmlUd0pLMHJFYjZoNGNoTDVmcElTVkxuQXBMVXRpdGJHdi9nVWRWMnRhVXFGQXptTlFIQVNUCnJ4T2hjR085MmQ2MVNWaEZ6TXI1MnQwZXluZXJoSE9JK1dvL2ZmcnBZS3NOMklhZTVVamFQUStaUE1pNGJ5ZC8KZy9NPQo9ZmJvMwotLS0tLUVORCBQR1AgU0lHTkFUVVJFLS0tLS0K
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: update-test-policy-test-namespace
      spec:
        remediationAction: enforce
        severity: High
        object-templates:
        - complianceType: musthave
          objectDefinition:
            kind: Namespace
            apiVersion: v1
            metadata:
              name: update-test-policy-test-ns
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: update-test-binding-policy-namespace
placementRef:
  name: update-test-placement-policy-namespace
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: update-test-policy-namespace
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: update-test-placement-policy-namespace
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
    - {key: environment, operator: In, values: ["dev"]}
