# This policy verifies the installation of Integrity Shield on the managed clusters.
# 
# "enforce", it will install Integirty Shield operator

apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-integrity-shield
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-5 Access Restrictions for Change
    integrityshield.io/message: H4sIALr1U2AAA+0ZXW/bNvDdv4JwHwoUpZpi6LDpzcuGrQ/Ngjrry9oHmjrLXCRSIyk3btH/viMp2bIjSs5XtwwlAjsmj/d9xzvyCblYCUMqVQi+IWvQYinAELsCIqSxrCiYFUoStSSvpYVcC7sh85WAIiM47eBKJlkOGeFFbSxok0yeEPybglwqzWH6nAhLPoqiaDEGTEJ3MFWgmVV6MmGVeIc4kGTaMJXgoqQNchqIlSBtItSL9cvJpZBZSs496KQEyzJmWTohRLISWhxUtLxT4yniOpNSWS+cceDkCHLIvcyYzkxKzl7PL8j8nPxwckJffXfkfs6QC6VRwSk5fUNOlVyKvNZBw2+2oMdiU9JqVXhc9BWZcQ7GkLdgrBbcy0XQAOR0xWQOE1MBd3Jq3J8JT3LmoVLSGAoXM2HYogBU6JIVxs00+rNQVugJ0KiKErX4C7j9GZZCCo/Fz7txYwu2G4Ml95TSmLWF6Jq3HYNmpm7VVMwLF0arh3bE9UGeePc+0IBHkFzbRTCIFIaPFlkGkiw2Ya8GjnAyJxXTyArKT9asqMFbph9T0mHOgItIu0nJbyJfdRaC+g/N0g5KuMIFwSSHi02F+ilR9yu2hj0wMmDFfaOcXVNjn7U7thyy2L7lrpmszQXUbNBfysflbyp/7I62+pccrWvG1gVMwpUG5b7KFz3eFSz4ewP9q1Z1dScP3Lpe3osqbPBxcKTfdsehP7TDMp2D3UaY6YNxmv5/BYqpF98i5cEihRXVisXiZV4vDNeictjvM2F/pXjhWM9IKFLihewBaKrM84LJWVVphdZNyay2qkST8nuRy6haO6FQ22Utu6nDRKHPdrpwYYdElhZjTl+CRYfpOVpxI+YGi656On83wF+yPkleJt8/rvjn+lv43z388X+TbHUbVBuMN5gBtp3cvG2G9sctkoABjYq55xRACKqBFeITyhs7FnkBTNZVsoPsUcjRyaVQeQ66n5YoMTxS8nfNNk7Hkdh5cU1KhxMdLt1F6QEvXnX3S7PBGSPJlt6/0Is/f+njyCMJAd/Pl78o2ARPrvIKA/Pq1cmP/SIEJ5tlpZB/IF9n3oGmweSpY1RwYJyrWto0IiDFb/eZZej1l2G5gGaChnzArS6m/RzIOUfE2wQ8hwJjTEVU7uCRgwxiy87rps/6SRECV+ObL+sF0CgGD7I7InrhjMgl6CELeaWIWDnpaMiRknPLywCngY8RBHOGqQ/mHjTKjXEmwlMmGPeBCY5goU2WO4JxTKmwaexAjIenATvFBe4X4sLUPtuPSAMlE1jB9JthRz2SH4MkN+PMANehJUkdAY3Zi4a5ng0aQn3j1ISA51otRRFvY/bKAm36uiw3sG6zqJq3dRRVQIc1HV8N6c8B4THpm8Mj6p5YSsgl1tf3w02NOU/eOgmmA9F4H/ibJBul4gux0xXwy/+KbdqxdxMcAUGsqsQq4ZxZRC8fGftuOMuea6wPr1Ly9FnydAAUmyD1cXvqhXvglFhd9/UabgQvn1k7lGC/qmLYMC+B1LStV5POnX7yfsqqygy1OCtlXHdFM6gKtXEX3++nY8F1V1qm03w/HDWzkZyGtPxwRLCTUpJjrsc6/qbiFGwBhSNyxDNHM+sc/yuQ8LHyQHS0UrapVuMUDu4Dx4pV7FkcA+NgJMTtL1fYAhuze/aKy4hH/zE3BcI0RVv8lWB/tG2fa0RHQH1rblLy59SlremHCaX01m+E7pbFzf6EPzEWe14LF2GFxl4NqxbFW1h23hjb2ei+bXbf7sezc0I6SXIk2CbdUpGOvm32nCY3yceHSh7LBNdV7OXreY0d1VTbmDeEsLbNROeNlro7MVujR0wvnEM07mN9IxpeULPTg62zNdbPLrvv0O5HSywuKPnsQwDkWmglHd/P95z3ecc/M1hPP3yZ/AP31ONbUB8AAA==
    integrityshield.io/signature: LS0tLS1CRUdJTiBQR1AgU0lHTkFUVVJFLS0tLS0KCmlRSFBCQUFCQ0FBNUZpRUVWSlRXK3hrWFZWcUdrSlRYZXJVUms4em81N0VGQW1CVDlib2JIR2hwY205cmRXNXAKTG10cGRHRm9ZWEpoTVVCcFltMHVZMjl0QUFvSkVIcTFFWlBNNk9leDVpVUwvMXBMNHB0bUxpd1ptSU9QZnRZOAo2MVp0V0VpOE11UE13ci9tS3l6QnZmN29yVDc0RHIrUmh4MU5YbVdaNU9PWWtCMzJOcWNJUkg1YUJHRDEzNmtXClB5b3JqazMzUDZVL1hqVnVrR1MwT2FyZUpNTWVJZDYzTmE4QnJERlE0ZUJJVCtqWHFsTURnMUFjOUZvYWsvbGEKRFcvelNZRkFQYUFZMEs4V290YnZ2dThyUGdZU1ZraTRzMFRVTUFIT2N4a0NpVFphMk81R3JsWldJQmRvTkhIMApJMTBNbUZhV0Z4T3NqVjMvU1JPanMrYjNlVCtSdHVzeU9PcjQxL3phR0dlM2VNalNmazBuS1MvNEo5M3YwRTBMClBobFoxT0M4S3RZYS9OV3JObVhJeXJ0S0ZndXZDdDJxOWlKWDdCSDVNUWN1ampOVU1nMUdEV3pQdklTNnRFOEIKWER1OGw2ZkY1cFBhNjJjbDF2Mk4yRWk4RE1yMkh1VzZFMEI1ZkpEMyt4d1M1SGszeEtNemdmMWpjdFhpSXYzcgpjVjFnK1puOGRTOFkyV1dKSlVReWgrRGpDRXFJdlgwVnlSNzBKTmVGREc1eDhxcFZLbFNFNmlZWkZmc2ozTDlrClZsNnJSYTBXT3lnaGRlZnRUTCs1VGRlM0NGcitWRVBQWEYySkR2RU5BNHFITmc9PQo9L3pSZgotLS0tLUVORCBQR1AgU0lHTkFUVVJFLS0tLS0K
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-integrity-shield-namespace
        spec:
          remediationAction: enforce # the policy-template spec.remediationAction is overridden by the preceding parameter value for spec.remediationAction.
          severity: High
          object-templates:
            - complianceType: musthave
              objectDefinition:
                kind: Namespace
                apiVersion: v1
                metadata:
                  name: integrity-shield-operator-system
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-integrity-shield-og
        spec:
          remediationAction: enforce # the policy-template spec.remediationAction is overridden by the preceding parameter value for spec.remediationAction.
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1
                kind: OperatorGroup
                metadata:
                  name: integrity-operator-group
                  namespace: integrity-shield-operator-system
                spec:
                  targetNamespaces:
                    - integrity-shield-operator-system
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-integrity-shield-sub
        spec:
          remediationAction: enforce # the policy-template spec.remediationAction is overridden by the preceding parameter value for spec.remediationAction.
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  name: integrity-shield-operator
                  namespace: integrity-shield-operator-system
                spec:
                  channel: alpha
                  installPlanApproval: Automatic
                  name: integrity-shield-operator
                  source: community-operators
                  sourceNamespace: openshift-marketplace
                  startingCSV: integrity-shield-operator.v0.1.6
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-integrity-shield-cr
        spec:
          remediationAction: enforce # the policy-template spec.remediationAction is overridden by the preceding parameter value for spec.remediationAction.
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: apis.integrityshield.io/v1alpha1
                kind: IntegrityShield
                metadata:
                  name: integrity-shield-server
                  namespace: integrity-shield-operator-system
                  finalizers:
                    - cleanup.finalizers.integrityshield.io
                spec:
                  logger:
                    image: quay.io/open-cluster-management/integrity-shield-logging:0.1.6
                  server:
                    image: quay.io/open-cluster-management/integrity-shield-server:0.1.6
                  affinity: {}
                  shieldConfig:
                    verifyType: pgp # x509
                    iShieldAdminUserName: "system:serviceaccount:open-cluster-management-agent-addon:klusterlet-addon-policyctrl"
                    inScopeNamespaceSelector:
                      include:
                        - "*"
                      exclude:
                        - "kube-*"
                        - "openshift-*"
                  signerConfig:
                    policies:
                      - namespaces:
                          - "*"
                        signers:
                          - SampleSigner
                      - scope: Cluster
                        signers:
                          - SampleSigner
                    signers:
                      - name: SampleSigner
                        keyConfig: sample-signer-keyconfig
                        subjects:
                          - email: "*"
                  keyConfig:
                    - name: sample-signer-keyconfig
                      secretName: keyring-secret
                  resourceSigningProfiles:
                    - name: policy-rsp
                      protectRules:
                        - match:
                            - apiGroup: policy.open-cluster-management.io
                      ignoreRules:
                        - match:
                            - username: "system:serviceaccount:open-cluster-management-agent:*"
                            - username: "system:serviceaccount:open-cluster-management-agent-addon:*"
                      forceCheckRules:
                        - match:
                            - apiGroup: policy.open-cluster-management.io
                              kind: Policy
                      kustomizePatterns:
                        - match:
                            - apiGroup: policy.open-cluster-management.io
                              kind: Policy
                          namePrefix: '*.'
                          allowNamespaceChange: true
                      ignoreAttrs:
                        - match:
                            - apiGroup: policy.open-cluster-management.io
                          attrs:
                            - "metadata.annotations.\"apps.open-cluster-management.io/hosting-deployable\""
                            - "metadata.annotations.\"apps.open-cluster-management.io/hosting-subscription\""
                            - "metadata.annotations.\"apps.open-cluster-management.io/sync-source\""
                            - "metadata.annotations.\"apps.open-cluster-management.io/reconcile-option\""
                            - "metadata.labels.\"policy.open-cluster-management.io/cluster-name\""
                            - "metadata.labels.\"policy.open-cluster-management.io/cluster-namespace\""
                            - "metadata.labels.\"policy.open-cluster-management.io/root-policy\""
                      targetNamespaceSelector:
                        labelSelector:
                          matchExpressions:
                            - key: policy.open-cluster-management.io/isClusterNamespace
                              operator: In
                              values: ["true"]
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-integrity-shield
  annotations:
    integrityshield.io/message: H4sIALr1U2AAA+0ZXW/bNvDdv4JwHwoUpZpi6LDpzcuGrQ/Ngjrry9oHmjrLXCRSIyk3btH/viMp2bIjSs5XtwwlAjsmj/d9xzvyCblYCUMqVQi+IWvQYinAELsCIqSxrCiYFUoStSSvpYVcC7sh85WAIiM47eBKJlkOGeFFbSxok0yeEPybglwqzWH6nAhLPoqiaDEGTEJ3MFWgmVV6MmGVeIc4kGTaMJXgoqQNchqIlSBtItSL9cvJpZBZSs496KQEyzJmWTohRLISWhxUtLxT4yniOpNSWS+cceDkCHLIvcyYzkxKzl7PL8j8nPxwckJffXfkfs6QC6VRwSk5fUNOlVyKvNZBw2+2oMdiU9JqVXhc9BWZcQ7GkLdgrBbcy0XQAOR0xWQOE1MBd3Jq3J8JT3LmoVLSGAoXM2HYogBU6JIVxs00+rNQVugJ0KiKErX4C7j9GZZCCo/Fz7txYwu2G4Ml95TSmLWF6Jq3HYNmpm7VVMwLF0arh3bE9UGeePc+0IBHkFzbRTCIFIaPFlkGkiw2Ya8GjnAyJxXTyArKT9asqMFbph9T0mHOgItIu0nJbyJfdRaC+g/N0g5KuMIFwSSHi02F+ilR9yu2hj0wMmDFfaOcXVNjn7U7thyy2L7lrpmszQXUbNBfysflbyp/7I62+pccrWvG1gVMwpUG5b7KFz3eFSz4ewP9q1Z1dScP3Lpe3osqbPBxcKTfdsehP7TDMp2D3UaY6YNxmv5/BYqpF98i5cEihRXVisXiZV4vDNeictjvM2F/pXjhWM9IKFLihewBaKrM84LJWVVphdZNyay2qkST8nuRy6haO6FQ22Utu6nDRKHPdrpwYYdElhZjTl+CRYfpOVpxI+YGi656On83wF+yPkleJt8/rvjn+lv43z388X+TbHUbVBuMN5gBtp3cvG2G9sctkoABjYq55xRACKqBFeITyhs7FnkBTNZVsoPsUcjRyaVQeQ66n5YoMTxS8nfNNk7Hkdh5cU1KhxMdLt1F6QEvXnX3S7PBGSPJlt6/0Is/f+njyCMJAd/Pl78o2ARPrvIKA/Pq1cmP/SIEJ5tlpZB/IF9n3oGmweSpY1RwYJyrWto0IiDFb/eZZej1l2G5gGaChnzArS6m/RzIOUfE2wQ8hwJjTEVU7uCRgwxiy87rps/6SRECV+ObL+sF0CgGD7I7InrhjMgl6CELeaWIWDnpaMiRknPLywCngY8RBHOGqQ/mHjTKjXEmwlMmGPeBCY5goU2WO4JxTKmwaexAjIenATvFBe4X4sLUPtuPSAMlE1jB9JthRz2SH4MkN+PMANehJUkdAY3Zi4a5ng0aQn3j1ISA51otRRFvY/bKAm36uiw3sG6zqJq3dRRVQIc1HV8N6c8B4THpm8Mj6p5YSsgl1tf3w02NOU/eOgmmA9F4H/ibJBul4gux0xXwy/+KbdqxdxMcAUGsqsQq4ZxZRC8fGftuOMuea6wPr1Ly9FnydAAUmyD1cXvqhXvglFhd9/UabgQvn1k7lGC/qmLYMC+B1LStV5POnX7yfsqqygy1OCtlXHdFM6gKtXEX3++nY8F1V1qm03w/HDWzkZyGtPxwRLCTUpJjrsc6/qbiFGwBhSNyxDNHM+sc/yuQ8LHyQHS0UrapVuMUDu4Dx4pV7FkcA+NgJMTtL1fYAhuze/aKy4hH/zE3BcI0RVv8lWB/tG2fa0RHQH1rblLy59SlremHCaX01m+E7pbFzf6EPzEWe14LF2GFxl4NqxbFW1h23hjb2ei+bXbf7sezc0I6SXIk2CbdUpGOvm32nCY3yceHSh7LBNdV7OXreY0d1VTbmDeEsLbNROeNlro7MVujR0wvnEM07mN9IxpeULPTg62zNdbPLrvv0O5HSywuKPnsQwDkWmglHd/P95z3ecc/M1hPP3yZ/AP31ONbUB8AAA==
    integrityshield.io/signature: LS0tLS1CRUdJTiBQR1AgU0lHTkFUVVJFLS0tLS0KCmlRSFBCQUFCQ0FBNUZpRUVWSlRXK3hrWFZWcUdrSlRYZXJVUms4em81N0VGQW1CVDlib2JIR2hwY205cmRXNXAKTG10cGRHRm9ZWEpoTVVCcFltMHVZMjl0QUFvSkVIcTFFWlBNNk9leDVpVUwvMXBMNHB0bUxpd1ptSU9QZnRZOAo2MVp0V0VpOE11UE13ci9tS3l6QnZmN29yVDc0RHIrUmh4MU5YbVdaNU9PWWtCMzJOcWNJUkg1YUJHRDEzNmtXClB5b3JqazMzUDZVL1hqVnVrR1MwT2FyZUpNTWVJZDYzTmE4QnJERlE0ZUJJVCtqWHFsTURnMUFjOUZvYWsvbGEKRFcvelNZRkFQYUFZMEs4V290YnZ2dThyUGdZU1ZraTRzMFRVTUFIT2N4a0NpVFphMk81R3JsWldJQmRvTkhIMApJMTBNbUZhV0Z4T3NqVjMvU1JPanMrYjNlVCtSdHVzeU9PcjQxL3phR0dlM2VNalNmazBuS1MvNEo5M3YwRTBMClBobFoxT0M4S3RZYS9OV3JObVhJeXJ0S0ZndXZDdDJxOWlKWDdCSDVNUWN1ampOVU1nMUdEV3pQdklTNnRFOEIKWER1OGw2ZkY1cFBhNjJjbDF2Mk4yRWk4RE1yMkh1VzZFMEI1ZkpEMyt4d1M1SGszeEtNemdmMWpjdFhpSXYzcgpjVjFnK1puOGRTOFkyV1dKSlVReWgrRGpDRXFJdlgwVnlSNzBKTmVGREc1eDhxcFZLbFNFNmlZWkZmc2ozTDlrClZsNnJSYTBXT3lnaGRlZnRUTCs1VGRlM0NGcitWRVBQWEYySkR2RU5BNHFITmc9PQo9L3pSZgotLS0tLUVORCBQR1AgU0lHTkFUVVJFLS0tLS0K
placementRef:
  name: placement-policy-integrity-shield
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: policy-integrity-shield
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-integrity-shield
  annotations:
    integrityshield.io/message: H4sIALr1U2AAA+0ZXW/bNvDdv4JwHwoUpZpi6LDpzcuGrQ/Ngjrry9oHmjrLXCRSIyk3btH/viMp2bIjSs5XtwwlAjsmj/d9xzvyCblYCUMqVQi+IWvQYinAELsCIqSxrCiYFUoStSSvpYVcC7sh85WAIiM47eBKJlkOGeFFbSxok0yeEPybglwqzWH6nAhLPoqiaDEGTEJ3MFWgmVV6MmGVeIc4kGTaMJXgoqQNchqIlSBtItSL9cvJpZBZSs496KQEyzJmWTohRLISWhxUtLxT4yniOpNSWS+cceDkCHLIvcyYzkxKzl7PL8j8nPxwckJffXfkfs6QC6VRwSk5fUNOlVyKvNZBw2+2oMdiU9JqVXhc9BWZcQ7GkLdgrBbcy0XQAOR0xWQOE1MBd3Jq3J8JT3LmoVLSGAoXM2HYogBU6JIVxs00+rNQVugJ0KiKErX4C7j9GZZCCo/Fz7txYwu2G4Ml95TSmLWF6Jq3HYNmpm7VVMwLF0arh3bE9UGeePc+0IBHkFzbRTCIFIaPFlkGkiw2Ya8GjnAyJxXTyArKT9asqMFbph9T0mHOgItIu0nJbyJfdRaC+g/N0g5KuMIFwSSHi02F+ilR9yu2hj0wMmDFfaOcXVNjn7U7thyy2L7lrpmszQXUbNBfysflbyp/7I62+pccrWvG1gVMwpUG5b7KFz3eFSz4ewP9q1Z1dScP3Lpe3osqbPBxcKTfdsehP7TDMp2D3UaY6YNxmv5/BYqpF98i5cEihRXVisXiZV4vDNeictjvM2F/pXjhWM9IKFLihewBaKrM84LJWVVphdZNyay2qkST8nuRy6haO6FQ22Utu6nDRKHPdrpwYYdElhZjTl+CRYfpOVpxI+YGi656On83wF+yPkleJt8/rvjn+lv43z388X+TbHUbVBuMN5gBtp3cvG2G9sctkoABjYq55xRACKqBFeITyhs7FnkBTNZVsoPsUcjRyaVQeQ66n5YoMTxS8nfNNk7Hkdh5cU1KhxMdLt1F6QEvXnX3S7PBGSPJlt6/0Is/f+njyCMJAd/Pl78o2ARPrvIKA/Pq1cmP/SIEJ5tlpZB/IF9n3oGmweSpY1RwYJyrWto0IiDFb/eZZej1l2G5gGaChnzArS6m/RzIOUfE2wQ8hwJjTEVU7uCRgwxiy87rps/6SRECV+ObL+sF0CgGD7I7InrhjMgl6CELeaWIWDnpaMiRknPLywCngY8RBHOGqQ/mHjTKjXEmwlMmGPeBCY5goU2WO4JxTKmwaexAjIenATvFBe4X4sLUPtuPSAMlE1jB9JthRz2SH4MkN+PMANehJUkdAY3Zi4a5ng0aQn3j1ISA51otRRFvY/bKAm36uiw3sG6zqJq3dRRVQIc1HV8N6c8B4THpm8Mj6p5YSsgl1tf3w02NOU/eOgmmA9F4H/ibJBul4gux0xXwy/+KbdqxdxMcAUGsqsQq4ZxZRC8fGftuOMuea6wPr1Ly9FnydAAUmyD1cXvqhXvglFhd9/UabgQvn1k7lGC/qmLYMC+B1LStV5POnX7yfsqqygy1OCtlXHdFM6gKtXEX3++nY8F1V1qm03w/HDWzkZyGtPxwRLCTUpJjrsc6/qbiFGwBhSNyxDNHM+sc/yuQ8LHyQHS0UrapVuMUDu4Dx4pV7FkcA+NgJMTtL1fYAhuze/aKy4hH/zE3BcI0RVv8lWB/tG2fa0RHQH1rblLy59SlremHCaX01m+E7pbFzf6EPzEWe14LF2GFxl4NqxbFW1h23hjb2ei+bXbf7sezc0I6SXIk2CbdUpGOvm32nCY3yceHSh7LBNdV7OXreY0d1VTbmDeEsLbNROeNlro7MVujR0wvnEM07mN9IxpeULPTg62zNdbPLrvv0O5HSywuKPnsQwDkWmglHd/P95z3ecc/M1hPP3yZ/AP31ONbUB8AAA==
    integrityshield.io/signature: LS0tLS1CRUdJTiBQR1AgU0lHTkFUVVJFLS0tLS0KCmlRSFBCQUFCQ0FBNUZpRUVWSlRXK3hrWFZWcUdrSlRYZXJVUms4em81N0VGQW1CVDlib2JIR2hwY205cmRXNXAKTG10cGRHRm9ZWEpoTVVCcFltMHVZMjl0QUFvSkVIcTFFWlBNNk9leDVpVUwvMXBMNHB0bUxpd1ptSU9QZnRZOAo2MVp0V0VpOE11UE13ci9tS3l6QnZmN29yVDc0RHIrUmh4MU5YbVdaNU9PWWtCMzJOcWNJUkg1YUJHRDEzNmtXClB5b3JqazMzUDZVL1hqVnVrR1MwT2FyZUpNTWVJZDYzTmE4QnJERlE0ZUJJVCtqWHFsTURnMUFjOUZvYWsvbGEKRFcvelNZRkFQYUFZMEs4V290YnZ2dThyUGdZU1ZraTRzMFRVTUFIT2N4a0NpVFphMk81R3JsWldJQmRvTkhIMApJMTBNbUZhV0Z4T3NqVjMvU1JPanMrYjNlVCtSdHVzeU9PcjQxL3phR0dlM2VNalNmazBuS1MvNEo5M3YwRTBMClBobFoxT0M4S3RZYS9OV3JObVhJeXJ0S0ZndXZDdDJxOWlKWDdCSDVNUWN1ampOVU1nMUdEV3pQdklTNnRFOEIKWER1OGw2ZkY1cFBhNjJjbDF2Mk4yRWk4RE1yMkh1VzZFMEI1ZkpEMyt4d1M1SGszeEtNemdmMWpjdFhpSXYzcgpjVjFnK1puOGRTOFkyV1dKSlVReWgrRGpDRXFJdlgwVnlSNzBKTmVGREc1eDhxcFZLbFNFNmlZWkZmc2ozTDlrClZsNnJSYTBXT3lnaGRlZnRUTCs1VGRlM0NGcitWRVBQWEYySkR2RU5BNHFITmc9PQo9L3pSZgotLS0tLUVORCBQR1AgU0lHTkFUVVJFLS0tLS0K
spec:
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: environment, operator: In, values: ["dev"]}
